# Use a valid Python base image (e.g., python:3.12.2)
FROM python:3.12.2-alpine

# Create user and set working directory
RUN addgroup -S mercari && adduser -S trainee -G mercari

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

WORKDIR /app
COPY . .

EXPOSE 9000

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "9000"]

